events {}

http {
  upstream auth {
    server auth:8080;
  }

  server {
    listen 80;
    server_name _;

    # ===== AUTH API =====
    location /api/auth/ {
      proxy_pass http://auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}