events {}

http {
  upstream frontend {
    server frontend:3000;
  }

  upstream auth {
    server auth:8080;
  }

  server {
    listen 80;
    server_name your-proj-name.com www.your-proj-name.com;
    return 301 https://$host$request_uri;
  }
  server {
    listen 443 ssl;
    server_name your-proj-name.com www.your-proj-name.com;

    ssl_certificate /etc/nginx/ssl/live/your-proj-name.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/your-proj-name.com/privkey.pem;

    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;  

    # ===== FRONTEND =====
    location / {
      proxy_pass http://frontend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ===== AUTH API =====
    location /api/auth/ {
      proxy_pass http://auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}